base_lr: 0.01
batch_size: 128
config: ./config/uav-cross-subjectv1/test.yaml
device:
- 0
- 1
- 2
- 3
eval_interval: 5
feeder: feeders.feeder.Feeder
ignore_weights: []
label_smoothing: 0.0
log_interval: 100
model: model.tegcn.Model
model_args:
  graph: graph.uav.Graph
  graph_args:
    labeling_mode: spatial
  num_class: 155
  num_person: 2
  num_point: 17
model_saved_name: runs/2996
nesterov: false
num_epoch: 80
num_worker: 32
only_train_epoch: 0
only_train_part: false
optimizer: SGD
phase: test
print_log: true
save_interval: 1
save_score: true
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 20
- 40
- 60
test_batch_size: 128
test_feeder_args:
  data_path: /home/srt16/code/ICMEW2024-Track10-main/data/test_joint.npy
  debug: false
  label_path: /home/srt16/code/ICMEW2024-Track10-main/data/test_label.npy
train_feeder_args: {}
warm_up_epoch: 0
weight_decay: 0.0005
weights: /home/srt16/code/TE-GCN-main/runs/2102-42-12814.pt
work_dir: work_dir/2996
