base_lr: 0.1
batch_size: 56
config: ./config/uav-cross-subjectv2/train.yaml
device:
- 0
eval_interval: 5
feeder: feeders.feeder.Feeder
ignore_weights: []
label_smoothing: 0.0
log_interval: 100
model: model.tegcn.Model
model_args:
  graph: graph.uav.Graph
  graph_args:
    labeling_mode: spatial
  num_class: 155
  num_person: 2
  num_point: 17
model_saved_name: runs/2102
nesterov: true
num_epoch: 50
num_worker: 32
only_train_epoch: 60
only_train_part: false
optimizer: SGD
phase: train
print_log: true
save_interval: 1
save_score: true
seed: 777
show_topk:
- 1
- 5
start_epoch: 0
step:
- 30
- 40
test_batch_size: 56
test_feeder_args:
  data_path: /home/srt16/code/ICMEW2024-Track10-main/data/val_joint.npy
  label_path: /home/srt16/code/ICMEW2024-Track10-main/data/val_label.npy
train_feeder_args:
  data_path: /home/srt16/code/ICMEW2024-Track10-main/data/train_joint.npy
  debug: false
  label_path: /home/srt16/code/ICMEW2024-Track10-main/data/train_label.npy
  normalization: false
  random_choose: false
  random_move: false
  random_shift: false
  window_size: -1
warm_up_epoch: 5
weight_decay: 0.0001
weights: null
work_dir: work_dir/2102
